// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function PerformUpdate(arg1) {
  return window['go']['main']['App']['PerformUpdate'](arg1);
}

export function Process(arg1) {
  return window['go']['main']['App']['Process'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}
