// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function GetCurrentVersion():Promise<string>;

export function PerformUpdate(arg1:string):Promise<boolean>;

export function Process(arg1:main.Config):Promise<main.ProcessResult>;

export function SelectFile():Promise<string>;

export function ShowInFolder(arg1:string):Promise<void>;
